# Generated by Django 5.1.4 on 2025-01-01 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('puzzles', '0002_alter_mathproblem_solution_alter_mathproblem_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='mathproblem',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
